name: Release
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 23 * * *"
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Release
        env:
          DATAFILLER_URL: ${{ secrets.DATAFILLER_URL }}
          NODE_OPTIONS: --insecure-http-parser
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn start
          if [[ "$(git status data/ --porcelain)" != "" ]]; then
            NOW=$(date +"%Y%m%d_%H%M")
            git add data
            git commit -m"feat(data): $NOW update" 
            npx semantic-release
          else
            echo "no changes detected"
          fi
